# NLP Exercises

We have five exercises in this section. The exercises are:
1. Build your own tokenizer, where you need to implement two functions to implement a tokenizer based on regular expression.
2. Get tags from Trump speech.
3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.
4. Build your own Bag Of Words implementation using tokenizer created before.
5. Build a 5-gram model and clean up the results.

## Exercise 1. Build your own tokenizer

Build two different tokenizers:
- ``tokenize_sentence``: function tokenizing text into sentences,
- ``tokenize_word``: function tokenizing text into words.

In [1]:
from typing import List
import re

def tokenize_words(text: str) -> list:
    """Tokenize text into words using regex.

    Parameters
    ----------
    text: str
            Text to be tokenized

    Returns
    -------
    List[str]
            List containing words tokenized from text

    """
    return re.split('\\s+', text)


def tokenize_sentence(text: str) -> list:
    """Tokenize text into words using regex.

    Parameters
    ----------
    text: str
            Text to be tokenized

    Returns
    -------
    List[str]
            List containing words tokenized from text

    """
    return re.split('(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?|\!)\s',text)

text = "Here we go again. I was supposed to add this text later. \
Well, it's 10.p.m. here, and I'm actually having fun making this course. :o\
I hope you are getting along fine with this presentation, I really did try. \
And one last sentence, just so you can test you tokenizers better."

print("Tokenized sentences:")
print(tokenize_sentence(text))

print("Tokenized words:")
print(tokenize_words(text))

Tokenized sentences:
['Here we go again.', 'I was supposed to add this text later.', "Well, it's 10.p.m. here, and I'm actually having fun making this course.", ':oI hope you are getting along fine with this presentation, I really did try.', 'And one last sentence, just so you can test you tokenizers better.']
Tokenized words:
['Here', 'we', 'go', 'again.', 'I', 'was', 'supposed', 'to', 'add', 'this', 'text', 'later.', 'Well,', "it's", '10.p.m.', 'here,', 'and', "I'm", 'actually', 'having', 'fun', 'making', 'this', 'course.', ':oI', 'hope', 'you', 'are', 'getting', 'along', 'fine', 'with', 'this', 'presentation,', 'I', 'really', 'did', 'try.', 'And', 'one', 'last', 'sentence,', 'just', 'so', 'you', 'can', 'test', 'you', 'tokenizers', 'better.']


## Exercise 2. Get tags from Trump speech using NLTK

You should use the ``trump.txt`` file, read it and find the tags for each word. Use NLTK for it.

In [29]:
!pip install nltk
import nltk

# Download the required data file
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('gutenberg')
nltk.download('genesis')
nltk.download('inaugural')
nltk.download('nps_chat')
nltk.download('webtext')
nltk.download('all')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!
[nltk_data] Downloading package genesis to /root/nltk_data...
[nltk_data]   Package genesis is already up-to-date!
[nltk_data] Downloading package inaugural to /root/nltk_data...
[nltk_data]   Package inaugural is already up-to-date!
[nltk_data] Downloading package nps_chat to /root/nltk_data...
[nltk_data]   Package nps_chat is already up-to-date!
[nltk_data] Downloading package webtext to /root/nltk_data...
[nltk_data]   Package webtext is already up-to-date!
[nltk_data] Downloading collect

True

In [9]:
file = open("trump.txt", "r",encoding="utf-8")
trump = file.read()
words = tokenize_words(trump)


tags = nltk.pos_tag(words)
tags

[('Thank', 'NNP'),
 ('you', 'PRP'),
 ('very', 'RB'),
 ('much.', 'VBP'),
 ('Mr.', 'NNP'),
 ('Speaker,', 'NNP'),
 ('Mr.', 'NNP'),
 ('Vice', 'NNP'),
 ('President,', 'NNP'),
 ('Members', 'NNP'),
 ('of', 'IN'),
 ('Congress,', 'NNP'),
 ('the', 'DT'),
 ('First', 'NNP'),
 ('Lady', 'NNP'),
 ('of', 'IN'),
 ('the', 'DT'),
 ('United', 'NNP'),
 ('States,', 'NNP'),
 ('and', 'CC'),
 ('citizens', 'NNS'),
 ('of', 'IN'),
 ('America:', 'NNP'),
 ('Tonight,', 'NNP'),
 ('as', 'IN'),
 ('we', 'PRP'),
 ('mark', 'VBP'),
 ('the', 'DT'),
 ('conclusion', 'NN'),
 ('of', 'IN'),
 ('our', 'PRP$'),
 ('celebration', 'NN'),
 ('of', 'IN'),
 ('Black', 'NNP'),
 ('History', 'NNP'),
 ('Month,', 'NNP'),
 ('we', 'PRP'),
 ('are', 'VBP'),
 ('reminded', 'VBN'),
 ('of', 'IN'),
 ('our', 'PRP$'),
 ("Nation's", 'NNP'),
 ('path', 'NN'),
 ('towards', 'NNS'),
 ('civil', 'JJ'),
 ('rights', 'NNS'),
 ('and', 'CC'),
 ('the', 'DT'),
 ('work', 'NN'),
 ('that', 'WDT'),
 ('still', 'RB'),
 ('remains', 'VBZ'),
 ('to', 'TO'),
 ('be', 'VB'),
 ('done

## Exercise 3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.

Please use Python list features to get the last 10 sentences and display nouns from it.

In [10]:
!pip install SpaCy

In [12]:
import spacy

file = open("trump.txt", "r",encoding='utf-8')
trump = file.read()

nlp = spacy.load("en_core_web_sm")
processed_text = nlp(trump)

# Get the last 10 sentences
for sentence in list(processed_text.sents)[-10:]:
    noun_chunks = list(sentence.noun_chunks)
    if noun_chunks:
        print("Noun chunks:")
        for chunk in noun_chunks:
            print(f"  - {chunk.text}")
    else:
        print("No noun chunks found.")


Noun chunks:
  - we
  - this vision
  - we
  - our 250 years
  - glorious freedom
  - we
  - tonight
  - this new chapter
  - American greatness
Noun chunks:
  - The time
  - small thinking
Noun chunks:
  - The time
  - trivial fights
  - us
Noun chunks:
  - We
  - the courage
  - the dreams
  - that
  - our hearts
  - the bravery
  - the hopes
  - that
  - our souls
  - the confidence
  - those hopes
  - those dreams
  - action
Noun chunks:
  - America
  - our aspirations
  - our fears
  - the future
  - failures
  - the past
  - our vision
  - our doubts
Noun chunks:
  - I
  - all citizens
  - this renewal
  - the American spirit
Noun chunks:
  - I
  - all Members
  - Congress
  - me
  - things
  - our country
Noun chunks:
  - I
  - everyone
  - this moment
Noun chunks:
  - yourselves
  - your future
  - America
Noun chunks:
  - you
  - God
  - you
  - God
  - the United States


## Exercise 4. Build your own Bag Of Words implementation using tokenizer created before

You need to implement following methods:

- ``fit_transform`` - gets a list of strings and returns matrix with it's BoW representation
- ``get_features_names`` - returns list of words corresponding to columns in BoW

In [17]:
import numpy as np
import spacy
import re

class BagOfWords:
    """Basic BoW implementation."""

    __nlp = spacy.load("en_core_web_sm")
    __bow_list = []

    def preprocess_text(self, text):
        text = text.lower()
        cleaned = re.sub(r'[\W_]+', ' ', text)

        return cleaned.strip()


    def fit_transform(self, corpus: list):
        """Transform list of strings into BoW array."""
        cleaned_texts = [self.preprocess_text(text) for text in corpus]
        tokenized_corpus = [tokenize_words(text) for text in cleaned_texts]

        vocab = sorted(set(word for doc in tokenized_corpus for word in doc))
        self.__bow_list = vocab

        bow_matrix = np.zeros((len(corpus), len(vocab)), dtype=int)
        for i, doc in enumerate(tokenized_corpus):
            for word in doc:
                if word in vocab:
                    j = vocab.index(word)
                    bow_matrix[i][j] += 1

        return bow_matrix

    def get_feature_names(self) -> list:
        return self.__bow_list

corpus = [
     'Bag Of Words is based on counting',
     'words occurences throughout multiple documents.',
     'This is the third document.',
     'As you can see most of the words occur only once.',
     'This gives us a pretty sparse matrix, see below. Really, see below',
]

vectorizer = BagOfWords()

X = vectorizer.fit_transform(corpus)
print(X)

print(vectorizer.get_feature_names())
len(vectorizer.get_feature_names())

[[0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1]
 [1 0 0 0 2 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 2 1 0 0 1 0 1 0 0]]
['a', 'as', 'bag', 'based', 'below', 'can', 'counting', 'document', 'documents', 'gives', 'is', 'matrix', 'most', 'multiple', 'occur', 'occurences', 'of', 'on', 'once', 'only', 'pretty', 'really', 'see', 'sparse', 'the', 'third', 'this', 'throughout', 'us', 'words', 'you']


31

## Exercise 5. Build a 5-gram model and clean up the results.

There are three tasks to do:
1. Use 5-gram model instead of 3.
2. Change to capital letter each first letter of a sentence.
3. Remove the whitespace between the last word in a sentence and . ! or ?.

Hint: for 2. and 3. implement a function called ``clean_generated()`` that takes the generated text and fix both issues at once. It could be easier to fix the text after it's generated rather then doing some changes in the while loop.

In [38]:
from nltk.book import *

wall_street = text7.tokens

import re
import random

tokens = wall_street

def cleanup():
    compiled_pattern = re.compile("^[a-zA-Z0-9.!?]")
    clean = list(filter(compiled_pattern.match,tokens))
    return clean
tokens = cleanup()

def build_ngrams():
    ngrams = []
    for i in range(len(tokens)-N+1):
        ngrams.append(tokens[i:i+N])
    return ngrams

def ngram_freqs(ngrams):
    counts = {}

    for ngram in ngrams:
        token_seq  = SEP.join(ngram[:-1])
        last_token = ngram[-1]

        if token_seq not in counts:
            counts[token_seq] = {}

        if last_token not in counts[token_seq]:
            counts[token_seq][last_token] = 0

        counts[token_seq][last_token] += 1;

    return counts

def next_word(text, N, counts):

    token_seq = SEP.join(text.split()[-(N-1):]);
    choices = counts[token_seq].items();

    total = sum(weight for choice, weight in choices)
    r = random.uniform(0, total)
    upto = 0
    for choice, weight in choices:
        upto += weight;
        if upto > r: return choice
    assert False # should not reach here

In [40]:
def clean_generated(text):
    text = re.sub(r'\s+([.!?])', r'\1', text)
    sentences = re.split(r'(?<=[.!?])\s+', text)
    capitalized = [s.strip().capitalize() for s in sentences]

    return ' '.join(capitalized)

N=5 # fix it for other value of N

SEP=" "

sentence_count=5

ngrams = build_ngrams()
start_seq="We have to be"

counts = ngram_freqs(ngrams)

if start_seq is None: start_seq = random.choice(list(counts.keys()))
generated = start_seq.lower();

sentences = 0
while sentences < sentence_count:
    generated += SEP + next_word(generated, N, counts)
    sentences += 1 if generated.endswith(('.','!', '?')) else 0

generated = clean_generated(generated)
print(generated)

We have to be more like the department store not the boutique. Iras. Sharedata inc. Said 0 it fired more than half its work force and is discontinuing its hardware business to focus on its core metals trading processing and plant engineering activities while shedding peripheral units the company said 0. The bush administration nomination of clarence thomas to a seat on the federal appeals court here received a blow this week when the supreme court refused to hear an appeal from a case that says 0 corporate defendants must pay damages even after proving that they could not possibly have caused the harm.
